server:
   port: 10003
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:10001/eureka/
spring:
   application:
      name: consumer-service

feign:
   hystrix:
      enabled: true
            