server:
   port: 10004
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:10001/eureka/
spring:
   application:
      name: zuul-service
      
zuul:
   routes:
      first-service:
         path: /first-service
         serviceId: FIRST-SERVICE
      consumer-service: 
         path: /consumer-service    
         serviceId: CONSUMER-SERVICE