server:
   port: 10001
   
eureka:
   instance:
      hostname: 127.0.0.1
   client:
      registerWithEureka: false
      fetchRegistry: false
      seviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   server:
      responseCacheUpdateIntervalMs: 3000 
      eviction-interval-timer-in-ms: 3000        

spring:
  application:
    name: eurka-server   