server:
   port: 10001
   
eureka:
   instance:
      hostname: 127.0.0.1
   client:
      registerWithEureka: false
      fetchRegistry: false
      seviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   

spring:
  application:
    name: eurka-server   