server:
   port: 10005
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:10001/eureka/
spring:
   application:
      name: config-service
   cloud:
      config:
         server:
            git:
               uri: https://github.com/653306065/spring-cloud-study/tree/master/config-service/src/main/resources/config
            searchPaths: respo
            username:
            password:
      label: master          
                 